name: ezolimo
description: Taking food security, sustainable agriculture and "plant pathology"
  beyond the moon.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.2.0
  cupertino_icons: ^1.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_lints: ^1.0.4
  flutter_secure_storage: ^4.2.1
  http: ^0.13.4
  http_parser: ^4.0.0
  hydrated_bloc: ^7.1.0
  image_picker: ^0.8.4+2
  mime: ^1.0.1

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
